`Communication`: Support File Sharing
ls1intum/artemis-ios pull request #260
Opened 2024-12-13 23:37 UTC by eylulnc

### Problem Description
This PR introduces a new feature that allows users to upload files directly to a conversation.

### Changes
 
**File Upload UI:**

Added buttons for file in message area

**Validation:**

Enforced a 5MB file size limit.
Restricted uploads to supported file types.

### Steps for testing
Test the new buttons added to the messsage field for file upload.
Upload a file or image and verify:
Files/images are displayed with appropriate markdown.

### Screenshots

<img width="370" alt="Screenshot 2024-12-14 at 00 32 17" src="https://github.com/user-attachments/assets/ac94f92c-6662-48bb-b6c1-e9d719a61b92" />

2024-12-13 23:57 UTC, anian03 requested changes
Looks pretty good overall now. Just some very small things that would be great if you could improve – otherwise we're good to go 😁

2024-12-13 23:57 UTC, anian03 commented on ArtemisKit/Sources/Messages/Services/MessagesService/MessagesServiceImpl.swift
> +       func uploadFile(for courseId: Int, and conversationId: Int64, file: Data, filename: String, mimeType: String) async -> DataState<String> {
Could we remove `uploadImage` and replace its usages with a call to this function? From what I can see it's the same, just with images using someUUID.jpg as fileName and Image/jpeg as mimeType.

2024-12-13 23:57 UTC, anian03 commented on ArtemisKit/Sources/Messages/Services/MessagesService/MessagesServiceImpl.swift
> +       }
```suggestion
        let path: String
    }
```

2024-12-13 23:57 UTC, anian03 commented on ArtemisKit/Sources/Messages/ViewModels/SendMessageViewModels/FileUpload/SendMessageUploadFileViewModel.swift
> +        Task {
I don't think we need to wrap this block inside a `Task` (we don't use async/await here).

2024-12-14 00:00 UTC, anian03 commented
Maybe something in general that we could think about for a follow up: Do we want to combine uploading images and files into a single button with a menu (like the + on the left)? I think that's how we do it on the web app, and most other apps do something similar

2024-12-14 00:27 UTC, eylulnc commented
> Maybe something in general that we could think about for a follow up: Do we want to combine uploading images and files into a single button with a menu (like the + on the left)? I think that's how we do it on the web app, and most other apps do something similar

I think we can discuss this and depending on the outcome also we create one more ticket for Android as well

2024-12-14 00:31 UTC, anian03 approved these changes
Thanks for the changes!

2024-12-14 00:35 UTC, merged